### ISSUE TITLE
Grammar Errors on Week 2

### ISSUE THREAD

**Issue by guti21js** [hunter-college-ossd-spr19/johncgenere-weekly#1]
For the following recommendations I am referring to this blog post:
https://hunter-college-ossd-spr19.github.io/johncgenere-weekly/week02/

In the second paragraph about contributions, the third sentence states " I want my next contribution(s) to be for the same reason as to why I wanted to contribute to CKB-Next;". I recommend cutting out "be for" for "have so that it states " I want my next contribution(s) to have the same reason as to why I wanted to contribute to CKB-Next;". I believe this makes it a easier to comprehend. 

In the same paragraph some markup does not work so a link shows up as "[Github’s How to Contribute to Open Source] (https://opensource.guide/how-to-contribute/)". I believe it might have to do with the forward slash at the end of the link. If you remove this the link should work.

**Comment by johncgenere** [comment]
Thank you for the recommendation and for making me aware of the link error! The link error was actually due to the space that was between the title and link; I went ahead and fixed it. In regards to the third sentence in the second paragraph about contributions, I think I will leave it as such. Again, thank you!
